Repository m20-sch57/thetruehat, pull requests merged in 2020-06, with the labels that each got.

#187 Fixed a bug with improper querystring in getRoomInfo
  server.js
Labels: back, bug

#192 Fixed a bug in getRoomInfo: added missing settings field
  server.js
Labels: back, bug

#195 Tooltip fix
  static/index.html
Labels: bug

#207 Replaced old fetch by flex_node_fetch
  fetch.js
  package-lock.json
  package.json
  server.js
Labels: back, enhancement

#200 READMEs update
  README.md
  README.ru.md
  localization/README.md
  package-lock.json
  package.json
Labels: documentation, invalid

#193 Stat collection
  .gitignore
  config.json
  docs/Web_API.md
  package-lock.json
  package.json
  server.js
  static/main.js
  version/post-checkout.hook
Labels: back, enhancement

#211 Исправлены проблемы с длительной загрузкой контента.
  Caddyfile
  static/main.js
Labels: bug, front

#215 version fix
  static/main.js
Labels: bug, front

#216 fixed bug with navigator permissions
  static/main.js
Labels: bug, front
