Repository m20-sch57/thetruehat, pull requests merged in 2020-08, with the labels that each got.

#267 Fixed ridiculous typos LOL
  package-lock.json
  package.json
  server.js
Labels: back, bug, invalid

#264 Now scores are dropped when copying users to next room
  server.js
Labels: back, bug

#259 Word selection server
  config.json
  package-lock.json
  package.json
  server.js
Labels: back, enhancement

#270 Fixed a bug with server
  server.js
Labels: back, bug

#268 Fixed incoordination in API
  docs/API_agreements.md
Labels: API, bug

#273 New cApplySettings and a bit more
  config.json
  docs/API_agreements.md
  server.js
Labels: back, bug

#271 Added dicts
  config.json
  words/easy
  words/easy.json
  words/easy_old
  words/easy_old.json
  words/hard
  words/hard.json
  words/med
  words/med.json
Labels: enhancement

#275 Rethinking of word choosing and a lot of more
  server.js
Labels: back, invalid

#282 Fixed bug with working through games with empty dictionaries
  server.js
Labels: back, bug

#281 fixed #280
  static/main.js
Labels: bug, front

#283 fixed #279
  static/main.js
Labels: bug, front

#288 s-problem
  config.json
  server.js
  static/config.js
  static/main.js
Labels: API, back, bug, front

#290 Server bug fix
  server.js
Labels: back, bug

#287 word selection
  config.json
  docs/API_agreements.md
  package-lock.json
  package.json
  server.js
  static/config.js
  static/index.html
  static/main.css
  static/main.js
  static/svg/arrow_down.svg
Labels: enhancement

#295 исправлена тень на странице редактирования
  static/main.css
  static/main.js
Labels: bug, front

#292 Updated timetable generator.
  config.json
  server.js
  static/main.js
Labels: invalid

#294 укорочены названия словарей
  config.json
Labels: front, invalid

#298 Fixed problem with svg on staging
  static/main.css
Labels: bug

#304 Added wordCollectionPage_goBack action
  static/main.js
Labels: bug, front

#296 Добавлена информация об угадывающем на экран delay-таймера объясняющего
  static/main.js
Labels: front, invalid

#306 Fixed bug
  static/index.html
Labels: bug, front

#309 Server bug fix
  server.js
Labels: back, bug
