Repository m20-sch57/thetruehat, pull requests merged in 2020-05, with the labels that each got.

#31 Fixed API bug.
  js/main.js
  server.js
Labels: API, back, bug

#32 Rewrited with new api
  js/main.js
Labels: front

#33 24 playing functions
  server.js
Labels: back, bug

#35 поправки в API
  docs/API.md
  docs/API_agreements.md
Labels: API, documentation

#26 Docs upgraded
  README.md
  README.ru.md
  docs/main.md
  docs/main.ru.md
  docs/site_map.md
  docs/site_map.ru.md
  setupServer.md
Labels: documentation

#18 Added state machine
  docs/clientFlowChart.pdf
  docs/clientStateMachine.pdf
  docs/serverStateMachine.pdf
Labels: API, documentation

#40 Страница редактирования, масштабирование слов, звуки обратного отсчёта.
  index.html
  server.js
  static/delayTimer.mp3
  static/main.css
  static/main.js
Labels: front

#41 Время спрашивается с сервера, подсказа под кнопкой начать игру.
  config.json
  index.html
  server.js
  static/main.css
  static/main.js
Labels: front

#49 Added errors. Changed code format.
  docs/errorsCodes.md
Labels: documentation

#51 Добавлены сообщения об ошибках
  index.html
  static/main.css
  static/main.js
Labels: front

#54 Code improvement
  server.js
Labels: back

#53 Added simplification of the name
  server.js
Labels: back

#62 Feedback server
  Caddyfile
  config.json
  feedbackServer.js
  package.json
  server.js
Labels: back

#63 Put Caddy files in order
  docs/caddyman.md
  run
  runCaddy
  stop
Labels: invalid

#65 Fixed a bug with rewriting feedback instead of adding
  feedbackServer.js
Labels: back, bug

#67 Caddyfile bug fix.
  Caddyfile
Labels: back, bug

#61 Исправлена ошибка, когда не вся информация отображается на экране.
  static/main.js
Labels: bug, front

#68 Страница фидбэка
  static/index.html
  static/main.css
  static/main.js
Labels: front

#70 Fixed rounds counter
  static/main.js
Labels: bug, front

#75 Added pages help, faq, about
  static/index.html
  static/main.css
  static/main.js
Labels: front

#57 Добавлены звуки обратного отсчета, начала, конца и конца+3с.
  static/delayTimer.mp3
  static/index.html
  static/main.js
  static/sounds/countdown.mp3
  static/sounds/final+.mp3
  static/sounds/final.mp3
  static/sounds/start.mp3
Labels: front

#80 New README
  Caddyfile
  LICENSE
  README.md
  README.ru.md
  docs/main.md
  docs/main.ru.md
Labels: documentation

#82 Fixed translation bug.
  README.ru.md
Labels: bug, documentation

#81 Отображение статуса игры. Сообщения об ошибках. Скрол на странице редактирования
  static/index.html
  static/main.css
  static/main.js
Labels: front

#88 Updated error server comments
  server.js
Labels: back, invalid

#95 Server asynchronous bug fixed
  server.js
Labels: back, bug

#96 Fixed you-are-not-in-the-room bug
  docs/errorsCodes.md
  server.js
Labels: back, bug

#97 Added reconnect handler
  static/main.js
Labels: front

#98 Fixed bug with checking properties
  static/main.js
Labels: bug, front

#103 Fixed problem with padding in firefox
  static/main.css
  static/main.js
Labels: bug, front

#101 Fixed scroll
  static/main.js
Labels: bug, front

#100 Fixed visual bug on edit page
  static/main.css
Labels: bug, front

#102 Общие исправления по дизайну
  static/main.css
Labels: bug, front

#131 All whitespaces removed from key
  server.js
  static/main.js
Labels: back, front

#134 Added fields and signals for room settings
  docs/Web_API.md
Labels: API

#127 Fixed Zinov Sombrero mentions
  static/about.html
Labels: invalid

#142 Added settings implementation
  config.json
  server.js
Labels: back, enhancement

#155 Fixed a bug with priority of operators
  server.js
Labels: back, bug

#160 Small server fix
  server.js
Labels: back, bug

#162 Server end game
  server.js
Labels: back, bug

#164 Fixed a bug with error messages
  server.js
Labels: back, bug

#165 Added english words
  config.json
  words/english-nouns.json
  words/english-nouns.txt
Labels: back, enhancement

#167 Fixed a bug with copying settings
  server.js
Labels: back, bug

#172 Fixed config
  config.json
Labels: back, bug

#175 Fixed problems with merge
  static/main.js
Labels: bug

#176 Fixed forEach in edge
  static/main.js
Labels: bug, front
