Repository m20-sch57/thetruehat, pull requests merged in 2020-04, with the labels that each got.

#17 change api in accordance with state machine
  docs/API.md
  docs/client_server_interaction.md
Labels: API, documentation

#6 MVP - first draft
  docs/MVP.md
Labels: TOR, documentation

#21 Code upgrade
  index.html
  js/main.js
  package-lock.json
  package.json
  server.js
Labels: back, front, invalid

#22 Updated API
  docs/API.md
  docs/API_agreements.md
Labels: API

#30 Th 23 organization functions
  js/main.js
  server.js
Labels: back
